usr/share/epiphany-browser/[!m]*                        usr/share/epiphany-browser
usr/share/epiphany-browser/mime-types-permissions.xml   etc/gnome/epiphany
usr/share/GConf/gsettings                               usr/share/GConf
usr/share/glib-2.0                                      usr/share
usr/share/help                                          usr/share
usr/share/locale                                        usr/share
